version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-node-app:latest .

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
