version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$MYPASSWORD" | docker login -u "$MYUSERNAME" --password-stdin
      - docker/build:
          image: cloudaccessnetwork/cicd
          tag: latest
      - docker/push:
          image: cloudaccessnetwork/cicd
          tag: latest
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 8080:8080 --name my-node-app-container cloudaccessnetwork/cicd:latest
      - run:
          name: Wait for Container to Start
          command: |
            sleep 10

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

