version: 2.1

orbs:
  docker: circleci/docker@2.3.0

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout

      - docker/publish:
          image: cloudaccessnetwork/cicd
          tag: latest
          dockerfile: Dockerfile
          username: $MYUSERNAME
          password: $MYPASSWORD

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
