name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t cicd:latest .

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --name my-node-app-container cicd:latest

      - name: Wait for Container to Start
        run: |
          sleep 10

      - name: Test Route
        run: |
          curl http://127.0.0.1:8080

      - name: Tag Docker Image
        run: |
          docker tag cicd:latest cloudaccessnetwork/cicd:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push cloudaccessnetwork/cicd:latest
